### PR TITLE
new producer issue template

### PR DESCRIPTION
**Pull request by jracusin**
# Description
Creating new issue template for onboarding new notice types, so that we have a streamlined procedure.  Each individual step should be its own PR.

# Related Issue(s)

# Testing

### CODE REVIEW

**Review by dakota002 — APPROVED** [review]

**Review by Vidushi-GitHub — APPROVED** [review]
Shall we put example as well, wherever possible?

**Review by lpsinger — COMMENTED** [review]
Why is this issue template at org scope? Why isn't it at project scope?

**Comment by jracusin** [comment]
Ok, I'll move it to the gcn.nasa.gov repo

**Comment by jracusin** [comment]
This template is meant for use as an organizational tool for us when onboard new producers, not for the producers to open themselves necessarily.

**Comment by lpsinger** [comment]
OK, but same question: on which repo will we open these issues? We can't open issues at the organization level, only at the project level. It only makes sense for this template to be defined at the project level if we might open these issues on any one of _several_ different projects.

**Comment by jracusin** [comment]
Replaced by PR nasa-gcn/gcn.nasa.gov/#2627

**Pull request closed without merging**
